export const GET_ERROR = "GET_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_MANAGER_PROFILE = "GET_MANAGER_PROFILE";

export const GET_RESTAURANT_PROFILE = "GET_RESTAURANT_PROFILE";
export const GET_COUNTRIES = "GET_COUNTRIES";

export const SEND_REPORT = "SEND_REPORT";
export const SEND_FEEDBACK = "SEND_FEEDBACK";

export const SET_HISTORY_LIST = "ORDER_HISTORY";
export const SET_KITCHEN_LIST = "SET_KITCHEN_LIST";
export const SET_WAITER_LIST = "SET_WAITER_LIST";
export const SET_CASHIER_LIST = "SET_CASHIER_LIST";
export const SET_CATEGORY = "SET_CATEGORY";
